services:
  auth-service:
    container_name: auth-service
    build: ./
    ports:
      - "8060:8060"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/jwt_security
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery:8761/actuator/health"]
      interval: 10s
      retries: 3
    networks:
      - config-server_net-bridge
networks:
  config-server_net-bridge:
    external: true