eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8070
spring:
  application:
    name: social-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/social
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    blog-url: http://gateway:8222/api/blogs
  security:
    jwt:
      secretKey: P4inmZExW3eMSf+dbS0VaDRaRK/Iu7ZTWiCCOyNwnbQGhB4JS5oPdxELOns7YeU

management:
  tracing:
    sampling:
      probability: 1.0